### ISSUE TITLE
length-range function does not take password as argument

### ISSUE THREAD

**Issue by S4G4R** [liquidz/clj-password-check#1]
`length-range` function only takes `min-length` or `max-length`, or both. But it does not actually take the password as argument

**Comment by liquidz** [comment]
@S4G4R `length-range` function generates a checker function.
https://github.com/liquidz/clj-password-check/blob/master/src/clj_password_check/core.clj#L99

You should use `combine-checkers` or bind as another var as follows.
```clojure
(def valid? (length-range 1 10))
(valid? "password")
```

**Comment by S4G4R** [comment]
@liquidz thank you for your help.
I have this block of code here :

```
(defn strong-password?
  "Checks if a password is strong enough.
   Should be atleast eight characters long, have atleast 
   one capital letter and atleast one number"
  [password]
  (let [conditions [not-blank? contains-uppercase?
                    contains-lowercase? contains-number?
                    (length-range 8)]
        checker (apply combine-checkers conditions)]
    #(checker password)))
```

I am new to the language so im not sure what I am doing wrong. Could you please help me fix the above code?

**EDIT** :

I fixed it by removing anonymous function call

`(checker password)`

Thank you again for your help.
